### ISSUE TITLE
Cannot find module './lib/compiler.js' in 2.6.0

### ISSUE THREAD

**Issue by sambernet** [ampedandwired/html-webpack-plugin#164]
In 2.6.0 release the compiler was extracted to its own file.

The extracted files are *not included in the npm package* published to the registry though (no /lib folder in node_modules/html-webpack-plugin).

Stack trace (running webpack build through gulp):
```
Error: Cannot find module './lib/compiler.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\dev\git\kw-advisory-gui\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\dev\git\kw-advisory-gui\webpack.config.js:5:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

When reverting to 2.5.0 all is well again.

Regards
Sam Bernet

**Comment by milyord** [comment]
Same here, it seems like your latest changes with moving stuff to ./lib/compiler.js never made it's way to npm. Try to re-publish.

**Comment by jantimon** [comment]
Oh sry forgot to update the `package.json` files array:
https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/package.json#L6

Will be fixed soon!
