### ISSUE TITLE
Cannot read undefined

### ISSUE THREAD

**Issue by jasonkuhrt** [ampedandwired/html-webpack-plugin#19]
I am stuck with this error when I try the default template:

```
nction(s,d){_s+=tmpl(s,d);},_s='<html'; if(o.htmlWebpackPlugin.files.manifest)
                                                                    ^
TypeError: Cannot read property 'manifest' of undefined
    at eval (eval at <anonymous> (/Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/node_modules/blueimp-tmpl/js/tmpl.js:26:65), <anonymous>:1:147)
    at tmpl (/Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/node_modules/blueimp-tmpl/js/tmpl.js:29:23)
    at HtmlWebpackPlugin.emitHtml (/Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/index.js:46:14)
    at /Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/index.js:37:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by jasonkuhrt** [comment]
When I try the custom config given in the readme I get another different error:

```
http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/jasonkuhrt/projects/react-popover/dev-build
undefined:4
})
 ^
SyntaxError: Unexpected token )
    at Function (native)
    at tmpl (/Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/node_modules/blueimp-tmpl/js/tmpl.js:26:65)
    at HtmlWebpackPlugin.emitHtml (/Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/index.js:46:14)
    at /Users/jasonkuhrt/projects/react-popover/node_modules/html-webpack-plugin/index.js:37:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by tomatau** [comment]
package.json

```
    "html-webpack-plugin": "ampedandwired/html-webpack-plugin",
```

I had the same issue - this fixed for me as it wasn't available on npm yet.

**Comment by ampedandwired** [comment]
Try again with the new version, sorry for the confusion.

**Comment by jasonkuhrt** [comment]
@ampedandwired For what its worth I've since started my own project that is inspired by this one https://github.com/jasonkuhrt/bootstrap-webpack-plugin.

**Comment by ampedandwired** [comment]
Nice one, looks like some neat features
