### ISSUE TITLE
URIError: Failed to decode param [...]

### ISSUE THREAD

**Issue by Zorgatone** [ampedandwired/html-webpack-plugin#210]
I'm using html-webpack-plugin 2.8.1 (latest), webpack 1.12.12 (latest), webpack-dev-server 1.14.1 (latest) and node 5.4.1 and I get this error:

```
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.16 kB       0
    chunk    {0} index.html 534 bytes [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 534 bytes {0} [built]
webpack: bundle is now VALID.
URIError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.assets[chunk]%%7D'
    at decodeURIComponent (native)
    at decode_param (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:557:18)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:216:15)
    at expressInit (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
```

**Comment by jantimon** [comment]
`o` does not exist anymore please read the migration guide

**Comment by Zorgatone** [comment]
I didn't write any code that uses that...

I just kept this config:
```JavaScript
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    // ...
    plugins: [
        new HtmlWebpackPlugin({
          template: 'template.html'
        })
    ]
};
```

**Comment by Zorgatone** [comment]
Oh you're right... I forgot the HTML template... Updating it

**Comment by jantimon** [comment]
:1 :)

**Comment by Zorgatone** [comment]
Oh wait I'm still getting the error anyway..

I'm posting my template.html.diff

```
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.15 kB       0
    chunk    {0} index.html 530 bytes [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 530 bytes {0} [built]
webpack: bundle is now VALID.
URIError: Failed to decode param '/%7B%=%20htmlWebpackPlugin.assets[chunk]%20%%7D'
    at decodeURIComponent (native)
    at decode_param (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:557:18)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:216:15)
    at expressInit (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
forgot
```

```diff
diff --git a/template.html b/template.html
index 951753c..ef149a5 100644
--- a/template.html
+++ b/template.html
@@ -3,10 +3,10 @@
 	<head>
 		<meta charset="utf-8" />
 		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />
-		<title>{%= o.htmlWebpackPlugin.options.pkg.description %}</title>
+		<title>{%= htmlWebpackPlugin.options.pkg.description %}</title>
 	</head>
 	<body ng-app="{%= o.htmlWebpackPlugin.options.pkg.name %}">
 		<ion-nav-view></ion-nav-view>
-		{% for (var chunk in o.htmlWebpackPlugin.assets) { %}<script src="{%=o.htmlWebpackPlugin.assets[chunk]%}"></script>{% } %}
+		{% for (var chunk in htmlWebpackPlugin.assets) { %}<script src="{%= htmlWebpackPlugin.assets[chunk] %}"></script>{% } %}
 	</body>
 </html>
```

**Comment by Zorgatone** [comment]
Hold on... Trying to get it to work, I'm having some trouble

**Comment by jantimon** [comment]
Well we switched from blueimp to underscore templates - as described in the migration document ;)

**Comment by jantimon** [comment]
Also inject is set to true by default

**Comment by Zorgatone** [comment]
This is what I tried to migrate my old template.html

What am I doing wrong here? I don't get it. :sob: 

```diff
diff --git a/template.html b/template.html
index 951753c..f6a908f 100644
--- a/template.html
+++ b/template.html
@@ -3,10 +3,10 @@
 	<head>
 		<meta charset="utf-8" />
 		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width" />
-		<title>{%= o.htmlWebpackPlugin.options.pkg.description %}</title>
+		<title>{%=htmlWebpackPlugin.options.pkg.description%}</title>
 	</head>
-	<body ng-app="{%= o.htmlWebpackPlugin.options.pkg.name %}">
+	<body ng-app="{%=htmlWebpackPlugin.options.pkg.name%}">
 		<ion-nav-view></ion-nav-view>
-		{% for (var chunk in o.htmlWebpackPlugin.assets) { %}<script src="{%=o.htmlWebpackPlugin.assets[chunk]%}"></script>{% } %}
+		{% for (var chunk in htmlWebpackPlugin.assets) { %}<script src="{%=htmlWebpackPlugin.assets[chunk]%}"></script>{% } %}
 	</body>
 </html>
```

And this is the error:
```
Child html-webpack-plugin for "template.html":
         Asset     Size  Chunks       Chunk Names
    template.html  2.15 kB       0
    chunk    {0} template.html 522 bytes [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./template.html 522 bytes {0} [built]
webpack: bundle is now VALID.
URIError: Failed to decode param '/%7B%=htmlWebpackPlugin.assets[chunk]%%7D'
    at decodeURIComponent (native)
    at decode_param (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:557:18)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:216:15)
    at expressInit (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
URIError: Failed to decode param '/%7B%=htmlWebpackPlugin.assets[chunk]%%7D'
    at decodeURIComponent (native)
    at decode_param (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:557:18)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:216:15)
    at expressInit (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/webdev1/repos/B-See/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/Users/webdev1/repos/B-See/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:312:13)
    at /Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/webdev1/repos/B-See/node_modules/express/lib/router/index.js:330:12)
```

**Comment by Zorgatone** [comment]
> blueimp to underscore templates
Is that a completely different syntax? I'm searching now

**Comment by Zorgatone** [comment]
Do I just need to change from `{% %}` to `<% %>`?

**Comment by Zorgatone** [comment]
Oh, anyway if you wonder what `pkg` is I defined it like this:

```JavaScript
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    // ...
    plugins: [
        new HtmlWebpackPlugin({
            pkg: require("./package.json"),
            template: 'template.html'
        })
    ]
};
```

**Comment by jantimon** [comment]
and set inject to false.
Are you using a html-loader for .html files?

**Comment by Zorgatone** [comment]
Yeah I think I am :sweat_smile: 

```JavaScript
//[...]
module: {
		loaders: [{
			test: /\.html$/,
			loader: "html"
		}
//[...]
```

**Comment by Zorgatone** [comment]
Like this?

```JavaScript
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    // ...
    plugins: [
        new HtmlWebpackPlugin({
            pkg: require("./package.json"),
            template: 'template.html',
            inject: false
        })
    ]
};
```

**Comment by Zorgatone** [comment]
I used `inject: false` and I have the same error `URIError: Failed to decode param '/%3C%-%20htmlWebpackPlugin.assets[chunk]%20%%3E'`

**Comment by jantimon** [comment]
Yoh have to rename the file from template.html to template.ejs so it is not touched by the html-loader.

**Comment by Zorgatone** [comment]
It worked thanks! I had to re-enable the inject though.

**Comment by dsebastien** [comment]
@jantimon thanks, that helped! :)

**Comment by jantimon** [comment]
cool :+1:

**Comment by paoloatienza** [comment]
@Zorgatone can I see your config for htmlWebpackPlugin? cause I have the same error right now and I did the migration guide but still cannot decode param error

**Comment by Zorgatone** [comment]
@paoloatienza I don't even remember what I was working on at the time, I'm using browserify on all of my projects now. I'm afraid I can't help you now
😢

**Comment by BernardoS** [comment]
I'm having the same trouble. I already changed the template to `.ejs` and yes I'm using `html-loader` with some limitations in the `include`, to ensure that it's not reading anything else.
```javascript
{
        test: /\.html$/,
        include: /views/,
        use: [
          {
            loader: 'file-loader',
            options: {name: 'assets/html/[name].[ext]'}
          },
          'extract-loader',
          'html-loader'
        ]
      }
```

and I'm having some troubles when it comes to access the template when it's not the `/` route path.
Let's say I set a `/test` path, then it pops out 
```html
<script async defer src="<%= htmlWebpackPlugin.files.chunks.app.entry %>"></script>
```

that's what I got in my folder.
![image](https://user-images.githubusercontent.com/5483269/28130037-fccb7e8a-670b-11e7-92cb-a70d6d71c627.png)

I preload the `home.html` in my `index.ejs` and my router declares 2 client-side routes (`/` and `/test`), the `/` one it's fine, but the other one, it seems like it doesn't see the template as `.ejs` file, cause clearly the `HtmlWebPackPlugin` is not parsing it in this case...

I also get the  `URIError: Failed to decode param '/%7B%=o.htmlWebpackPlugin.assets[chunk]%%7D'` error that @Zorgatone first declared in the web-pack-dev-server

here's my `.ejs`

````html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>web-router</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script src="<%= htmlWebpackPlugin.files.chunks.router.entry %>"></script>
    <link id="home" rel="import" href="<%= require('./views/home.html') %>">
  </head>
  <body>
    <web-browser-router disabled>
      <web-route id="home" path="/"></web-route>
      <web-route exact id="test" path="/test"></web-route>
    </web-browser-router>
    <script async defer src="<%= htmlWebpackPlugin.files.chunks.app.entry %>"></script>
  </body>
</html>
```

**Comment by iamzuijiasunyou** [comment]
@sunderhus  I have the same trouble when I use html-loader and HtmlWebPackPlugin to deal with html files. 
I also get the URIError: Failed to decode param '/%3C%=%20%20htmlWebpackPlugin.files.css[0]%20%%3E'
I wanna konw how do you fix it??
