### ISSUE TITLE
Conflict Error: Multiple assets emit to 'index.html' with webpack@2.1.0-beta.19

### ISSUE THREAD

**Issue by tomachristian** [ampedandwired/html-webpack-plugin#387]
When using multiple entries
```
entry: {
        "polyfills": "./polyfills.browser.ts",
        "main": "./main.browser.ts",
        "vendor": "./vendor.browser.ts"
    }
```

and HtmlWebpackPlugin like
```
plugins: [ new HtmlWebpackPlugin() ]
```

I get the following errors when executing 'webpack':

```
ERROR in chunk polyfills [entry]
index.html
Conflict: Multiple assets emit to the same filename 'index.html'
Error: Conflict: Multiple assets emit to the same filename 'index.html'
    at Compilation.createChunkAssets ([...]\node_modules\webpack\lib\Compilation.js:962:11)
    ...

ERROR in chunk main [entry]
index.html
Conflict: Multiple assets emit to the same filename 'index.html'
Error: Conflict: Multiple assets emit to the same filename 'index.html'
    at Compilation.createChunkAssets ([...]\node_modules\webpack\lib\Compilation.js:962:11)
    ...
```

When using detailed logging with the webpack command, I can see the following:

```
     Asset       Size  Chunks             Chunk Names
index.html  295 bytes       0  [emitted]  vendor
Entrypoint main =
Entrypoint polyfills =
Entrypoint vendor = index.html
chunk    {0} index.html (vendor) 569 bytes [entry] [rendered]
    [2] ./vendor.browser.ts 569 bytes {0} [built]
chunk    {1}  (polyfills) 550 bytes [entry] [rendered]
    [1] ./polyfills.browser.ts 550 bytes {1} [built]
chunk    {2}  (main) 645 bytes [entry] [rendered]
    [0] ./main.browser.ts 645 bytes {2} [built]
```

It seems that the 'index.html' is being set as the vendor entrypoint for whatever reason.

Without the HtmlWebpackPlugin, I get the correct output:

```
              Asset     Size  Chunks             Chunk Names
   vendor.bundle.js  2.61 kB       0  [emitted]  vendor
polyfills.bundle.js   2.6 kB       1  [emitted]  polyfills
     main.bundle.js  2.68 kB       2  [emitted]  main
Entrypoint main = main.bundle.js
Entrypoint polyfills = polyfills.bundle.js
Entrypoint vendor = vendor.bundle.js
```

**Comment by tomachristian** [comment]
The issue was using webpack.config.babel.js with babel-register, when dropping that, it works.
