### ISSUE TITLE
imcompatibility with webpack2-beta

### ISSUE THREAD

**Issue by lex93ushakov** [ampedandwired/html-webpack-plugin#454]
```sh
/home/lex93ushakov/lab/webpackStudy/webpack.config.js:13
                new HtmlWebpackPlugin({
                    ^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireConfig (/usr/lib/node_modules/webpack/bin/convert-argv.js:111:18)
    at /usr/lib/node_modules/webpack/bin/convert-argv.js:124:17
```

webpack.config.js
```js
const HtmlWebpackPlugin = require("html-webpack-plugin");                       
                                                                                
module.exports = {                                                              
  entry : {                                                                     
    app : "./app"                                                               
  },                                                                            
  output : {                                                                    
    path : "dist",                                                              
    filename : "bundle.js",                                                     
    library : "entry"                                                           
  },                                                                            
  plugins : {                                                                   
    new HtmlWebpackPlugin({                                                     
      title : "Webpack Study App",                                              
      hash : true                                                               
    })                                                                          
  },                                                                            
  loaders : {                                                                   
    {                                                                           
      test : /\.css$/,                                                          
      loader : "style-loader!css-loader"                                        
    }                                                                           
  },                                                                            
  watch : true,                                                                 
  watchOptions : {                                                              
    aggregateTimeout : 100                                                      
  }                                                                             
}
```

**Comment by jonrimmer** [comment]
This is a syntax error caused by your ```plugins``` property being an object instead of an array. Nothing to do with webpack 2.
